sudo: true
language: java
jdk:
  - openjdk11
  
install:
  gradle

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "gradle clean build -x test"
